### PR TITLE
Adding Rostock

### PR DESCRIPTION
**Pull request by kvlahromei**
See http://www.klarschiff-hro.de/api.php

### CODE REVIEW

**Comment by bensheldon** [comment]
Thanks!

**Comment by kvlahromei** [comment]
@bensheldon Thanks for merging! How long will it take, till we show up at the list? IMHO you just cache one day?

**Comment by bensheldon** [comment]
@kvlahromei oh, oops. I thought I had this set up with Continuous Deployment, but I guess not. I'll deploy it manually.

**Comment by kvlahromei** [comment]
@bensheldon Thank you, now we are online :+1:

**Pull request merged**
